=== arturzxc/SQL_XML_DB_TaxiCompany/XSD/Booking.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Booking">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="OperatorID" type="xs:positiveInteger" maxOccurs="1" minOccurs="1"/>
                <xs:element name="BookingDate" type="xs:date" maxOccurs="1" minOccurs="1"/>

                <xs:element name="BookingTime" type="xs:time" minOccurs="1" maxOccurs="1"/>
                <xs:element name="PickUpAddress" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:group ref="Address" maxOccurs="1" minOccurs="1"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="DestinationAddress" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:group ref="Address" maxOccurs="1" minOccurs="1"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="EstimatedTime" type="xs:positiveInteger"/>
                <xs:group ref="PassengerInfo" maxOccurs="1" minOccurs="1"/>

                <xs:element name="Status" maxOccurs="1" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="COMPLETE"/>
                            <xs:enumeration value="NOT COMPLETE"/>
                            <xs:enumeration value="CANCELLED"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="BookingInfo">
                    <xs:complexType>
                        <xs:choice maxOccurs="1" minOccurs="1">
                            <xs:element name="NormalBooking">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="DriverID" type="xs:positiveInteger"/>
                                        <xs:element name="ClientID" minOccurs="0" maxOccurs="1"
                                            type="xs:positiveInteger"/>
                                        <xs:element name="PickUpDate" type="xs:date" maxOccurs="1"
                                            minOccurs="1"/>
                                        <xs:element name="PickUpTime" type="xs:time" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="RegularBooking">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ClientID" type="xs:positiveInteger"
                                            minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="RepeatOn" minOccurs="1"
                                            maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="DriverID"
                                                  type="xs:positiveInteger"/>
                                                  <xs:element name="WeekDay" maxOccurs="1"
                                                  minOccurs="1">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="MONDAY"/>
                                                  <xs:enumeration value="TUESDAY"/>
                                                  <xs:enumeration value="WEDNESDAY"/>
                                                  <xs:enumeration value="THURSDAY"/>
                                                  <xs:enumeration value="FRIDAY"/>
                                                  <xs:enumeration value="SATURDAY"/>
                                                  <xs:enumeration value="SUNDAY"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>

                                                  <xs:element name="WeeklyInterval" maxOccurs="1"
                                                  minOccurs="1">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:integer">
                                                  <xs:pattern value="[0-4]"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>

                                                  <xs:element name="PickUpTime" type="xs:time"
                                                  maxOccurs="1"/>
                                                  <xs:element name="PickUpDate" type="xs:date"
                                                  maxOccurs="1" minOccurs="1"/>

                                                  <xs:element name="RegStatus" maxOccurs="1"
                                                  minOccurs="1">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="CANCELLED"/>
                                                  <xs:enumeration value="ONGOING"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="TimesComplete" minOccurs="1"
                                                  maxOccurs="1" type="xs:integer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                        <xs:attribute name="Type" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:group name="PassengerInfo">
        <xs:sequence>
            <xs:element name="Name" maxOccurs="1" minOccurs="1" type="xs:string"/>
            <xs:element name="PhoneNumber" maxOccurs="1" minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"
                        />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:group>

    <xs:group name="Address">
        <xs:sequence>
            <xs:element name="Street" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="HouseNo" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="County" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="PostCode" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="City" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:group>
</xs:schema>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking4.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>2</OperatorID>
    <BookingDate>2012-12-10</BookingDate>
    <BookingTime>19:32:00</BookingTime>
    <PickUpAddress>
        <Street>Sleepy Hickory Road</Street>
        <HouseNo>6</HouseNo>
        <PostCode>W1B1 AH</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Rustic Anchor Street</Street>
        <HouseNo>41</HouseNo>
        <PostCode>W1D2 DS</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>30</EstimatedTime>
    <Name>Barney</Name>
    <PhoneNumber>07553251275</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Normal">
        <NormalBooking>
		    <DriverID>16</DriverID>
			<PickUpDate>2012-12-07</PickUpDate>
    		<PickUpTime>20:12:00</PickUpTime>
	    </NormalBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking5.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>2</OperatorID>
    <BookingDate>2012-12-10</BookingDate>
    <BookingTime>20:44:00</BookingTime>
    <PickUpAddress>
        <Street>Blue Falls Street</Street>
        <HouseNo>7</HouseNo>
        <PostCode>W1J 9LE</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Sleepy Point Street</Street>
        <HouseNo>43</HouseNo>
        <PostCode>W36 JH</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>20</EstimatedTime>
    <Name>Will</Name>
    <PhoneNumber>07566545127</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Regular">
        <RegularBooking>
            <ClientID>1</ClientID>
            <RepeatOn>
			    <DriverID>15</DriverID>
                <WeekDay>TUESDAY</WeekDay>
                <WeeklyInterval>2</WeeklyInterval>
                <PickUpTime>12:30:00</PickUpTime>
                <PickUpDate>2012-12-11</PickUpDate>
                <RegStatus>ONGOING</RegStatus>
				<TimesComplete>1</TimesComplete>
            </RepeatOn>
        </RegularBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking14.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>1</OperatorID>
    <BookingDate>2012-12-13</BookingDate>
    <BookingTime>20:22:00</BookingTime>
    <PickUpAddress>
        <Street>Sleepy Point Street</Street>
        <HouseNo>43</HouseNo>
        <PostCode>W36 JH</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Rustic Anchor Street</Street>
        <HouseNo>41</HouseNo>
        <PostCode>W1D 2DS</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>10</EstimatedTime>
    <Name>Nicky</Name>
    <PhoneNumber>07555451295</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Regular">
        <RegularBooking>
            <ClientID>7</ClientID>
            <RepeatOn>
			    <DriverID>16</DriverID>
                <WeekDay>MONDAY</WeekDay>
                <WeeklyInterval>2</WeeklyInterval>
                <PickUpTime>22:00:00</PickUpTime>
                <PickUpDate>2012-12-24</PickUpDate>
                <RegStatus>ONGOING</RegStatus>
				<TimesComplete>0</TimesComplete>
            </RepeatOn>
        </RegularBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking16.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>1</OperatorID>
    <BookingDate>2012-12-14</BookingDate>
    <BookingTime>19:01:00</BookingTime>
    <PickUpAddress>
        <Street>Queensbury Street</Street>
        <HouseNo>23</HouseNo>
        <PostCode>W13 9TY</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Omah Street</Street>
        <HouseNo>32</HouseNo>
        <PostCode>W1D 5PH</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>20</EstimatedTime>
    <Name>Ben</Name>
    <PhoneNumber>07555001275</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Normal">
      <NormalBooking>
			<DriverID>12</DriverID>
			<PickUpDate>2012-12-09</PickUpDate>
    		<PickUpTime>08:30:00</PickUpTime>
	  </NormalBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking7.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>3</OperatorID>
    <BookingDate>2012-12-11</BookingDate>
    <BookingTime>15:10:00</BookingTime>
    <PickUpAddress>
        <Street>Windy Swan Street</Street>
        <HouseNo>89</HouseNo>
        <PostCode>W1H 6HP</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Big Vale Street</Street>
        <HouseNo>12</HouseNo>
        <PostCode>W52 SZ</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>30</EstimatedTime>
    <Name>Jeff</Name>
    <PhoneNumber>07555451255</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Regular">
        <RegularBooking>
            <ClientID>1</ClientID>
            <RepeatOn>
			    <DriverID>2</DriverID>
                <WeekDay>WEDNESDAY</WeekDay>
                <WeeklyInterval>1</WeeklyInterval>
                <PickUpTime>16:05:00</PickUpTime>
                <PickUpDate>2012-12-12</PickUpDate>
                <RegStatus>CANCELLED</RegStatus>
				<TimesComplete>1</TimesComplete>
            </RepeatOn>
        </RegularBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking17.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>7</OperatorID>
    <BookingDate>2012-12-13</BookingDate>
    <BookingTime>10:09:00</BookingTime>
    <PickUpAddress>
        <Street>Windy Swan Street</Street>
        <HouseNo>89</HouseNo>
        <PostCode>W1H 6HP</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Sleepy Point Street</Street>
        <HouseNo>43</HouseNo>
        <PostCode>W36 JH</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>20</EstimatedTime>
    <Name>Johnson</Name>
    <PhoneNumber>07566545127</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Regular">
        <RegularBooking>
            <ClientID>6</ClientID>
			<RepeatOn>
				<DriverID>11</DriverID>
				<WeekDay>WEDNESDAY</WeekDay>
				<WeeklyInterval>4</WeeklyInterval>
				<PickUpTime>00:10:00</PickUpTime>
				<PickUpDate>2012-12-19</PickUpDate>
				<RegStatus>ONGOING</RegStatus>
				<TimesComplete>1</TimesComplete>
            </RepeatOn>
        </RegularBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>1</OperatorID>
    <BookingDate>2012-10-11</BookingDate>
    <BookingTime>11:09:00</BookingTime>
    <PickUpAddress>
        <Street>Sunny Bluff Road</Street>
        <HouseNo>51</HouseNo>
        <PostCode>W71 DA</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Amber Trace Street</Street>
        <HouseNo>56</HouseNo>
        <PostCode>W139RR</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>30</EstimatedTime>
    <Name>Thomas</Name>
    <PhoneNumber>07555451275</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Normal">
        <NormalBooking>
		    <DriverID>1</DriverID>
			<PickUpDate>2012-12-05</PickUpDate>
    		<PickUpTime>12:22:00</PickUpTime>
	    </NormalBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>1</OperatorID>
    <BookingDate>2012-12-10</BookingDate>
    <BookingTime>13:10:00</BookingTime>
    <PickUpAddress>
        <Street>Silver Flower Street</Street>
        <HouseNo>2</HouseNo>
        <PostCode>W120TE</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Sunny Bluff Road</Street>
        <HouseNo>51</HouseNo>
        <PostCode>W71 DA</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>60</EstimatedTime>
    <Name>James</Name>
    <PhoneNumber>07555431275</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Normal">
        <NormalBooking>
		    <DriverID>2</DriverID>
			<PickUpDate>2012-12-05</PickUpDate>
    		<PickUpTime>17:30:00</PickUpTime>
		</NormalBooking>
    </BookingInfo>
</Booking>
