=== arturzxc/SQL_XML_DB_TaxiCompany/XSD/Booking.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Booking">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="OperatorID" type="xs:positiveInteger" maxOccurs="1" minOccurs="1"/>
                <xs:element name="BookingDate" type="xs:date" maxOccurs="1" minOccurs="1"/>

                <xs:element name="BookingTime" type="xs:time" minOccurs="1" maxOccurs="1"/>
                <xs:element name="PickUpAddress" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:group ref="Address" maxOccurs="1" minOccurs="1"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="DestinationAddress" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:group ref="Address" maxOccurs="1" minOccurs="1"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="EstimatedTime" type="xs:positiveInteger"/>
                <xs:group ref="PassengerInfo" maxOccurs="1" minOccurs="1"/>

                <xs:element name="Status" maxOccurs="1" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="COMPLETE"/>
                            <xs:enumeration value="NOT COMPLETE"/>
                            <xs:enumeration value="CANCELLED"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="BookingInfo">
                    <xs:complexType>
                        <xs:choice maxOccurs="1" minOccurs="1">
                            <xs:element name="NormalBooking">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="DriverID" type="xs:positiveInteger"/>
                                        <xs:element name="ClientID" minOccurs="0" maxOccurs="1"
                                            type="xs:positiveInteger"/>
                                        <xs:element name="PickUpDate" type="xs:date" maxOccurs="1"
                                            minOccurs="1"/>
                                        <xs:element name="PickUpTime" type="xs:time" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="RegularBooking">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ClientID" type="xs:positiveInteger"
                                            minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="RepeatOn" minOccurs="1"
                                            maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="DriverID"
                                                  type="xs:positiveInteger"/>
                                                  <xs:element name="WeekDay" maxOccurs="1"
                                                  minOccurs="1">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="MONDAY"/>
                                                  <xs:enumeration value="TUESDAY"/>
                                                  <xs:enumeration value="WEDNESDAY"/>
                                                  <xs:enumeration value="THURSDAY"/>
                                                  <xs:enumeration value="FRIDAY"/>
                                                  <xs:enumeration value="SATURDAY"/>
                                                  <xs:enumeration value="SUNDAY"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>

                                                  <xs:element name="WeeklyInterval" maxOccurs="1"
                                                  minOccurs="1">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:integer">
                                                  <xs:pattern value="[0-4]"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>

                                                  <xs:element name="PickUpTime" type="xs:time"
                                                  maxOccurs="1"/>
                                                  <xs:element name="PickUpDate" type="xs:date"
                                                  maxOccurs="1" minOccurs="1"/>

                                                  <xs:element name="RegStatus" maxOccurs="1"
                                                  minOccurs="1">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="CANCELLED"/>
                                                  <xs:enumeration value="ONGOING"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="TimesComplete" minOccurs="1"
                                                  maxOccurs="1" type="xs:integer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                        <xs:attribute name="Type" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:group name="PassengerInfo">
        <xs:sequence>
            <xs:element name="Name" maxOccurs="1" minOccurs="1" type="xs:string"/>
            <xs:element name="PhoneNumber" maxOccurs="1" minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"
                        />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:group>

    <xs:group name="Address">
        <xs:sequence>
            <xs:element name="Street" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="HouseNo" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="County" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="PostCode" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="City" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:group>
</xs:schema>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking8.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>3</OperatorID>
    <BookingDate>2012-12-11</BookingDate>
    <BookingTime>15:32:00</BookingTime>
    <PickUpAddress>
        <Street>Little Branch Road</Street>
        <HouseNo>2</HouseNo>
        <PostCode>W120QG</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Granville Place</Street>
        <HouseNo>44</HouseNo>
        <PostCode>W84 QX</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>40</EstimatedTime>
    <Name>Nicky</Name>
    <PhoneNumber>07555001275</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Regular">
        <RegularBooking>
            <ClientID>3</ClientID>
            <RepeatOn>
			    <DriverID>15</DriverID>
                <WeekDay>FRIDAY</WeekDay>
                <WeeklyInterval>2</WeeklyInterval>
                <PickUpTime>09:20:00</PickUpTime>
                <PickUpDate>2012-12-14</PickUpDate>
                <RegStatus>ONGOING</RegStatus>
				<TimesComplete>2</TimesComplete>
            </RepeatOn>
        </RegularBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking10.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>5</OperatorID>
    <BookingDate>2012-12-12</BookingDate>
    <BookingTime>08:22:00</BookingTime>
    <PickUpAddress>
        <Street>Anadel Road</Street>
        <HouseNo>46</HouseNo>
        <PostCode>W42 RA</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Silver Flower Street</Street>
        <HouseNo>2</HouseNo>
        <PostCode>W12 0TE</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>60</EstimatedTime>
    <Name>Malfred</Name>
    <PhoneNumber>07555431275</PhoneNumber>
    <Status>CANCELLED</Status>
    <BookingInfo Type="Regular">
        <RegularBooking>
            <ClientID>5</ClientID>
            <RepeatOn>
			    <DriverID>16</DriverID>
                <WeekDay>WEDNESDAY</WeekDay>
                <WeeklyInterval>3</WeeklyInterval>
                <PickUpTime>23:10:00</PickUpTime>
                <PickUpDate>2012-12-19</PickUpDate>
                <RegStatus>CANCELLED</RegStatus>
				<TimesComplete>0</TimesComplete>
            </RepeatOn>
        </RegularBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking6.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>3</OperatorID>
    <BookingDate>2012-12-11</BookingDate>
    <BookingTime>14:20:00</BookingTime>
    <PickUpAddress>
        <Street>Shady River Street</Street>
        <HouseNo>4</HouseNo>
        <PostCode>W1H 1DN</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Lone Castle Road</Street>
        <HouseNo>65</HouseNo>
        <PostCode>W41 BH</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>10</EstimatedTime>
    <Name>Zan</Name>
    <PhoneNumber>07555451295</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Regular">
        <RegularBooking>
            <ClientID>1</ClientID>
            <RepeatOn>
			    <DriverID>15</DriverID>
                <WeekDay>MONDAY</WeekDay>
                <WeeklyInterval>3</WeeklyInterval>
                <PickUpTime>14:50:00</PickUpTime>
                <PickUpDate>2012-12-10</PickUpDate>
                <RegStatus>CANCELLED</RegStatus>
				<TimesComplete>3</TimesComplete>
            </RepeatOn>
        </RegularBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking15.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>5</OperatorID>
    <BookingDate>2012-12-14</BookingDate>
    <BookingTime>12:01:00</BookingTime>
    <PickUpAddress>
        <Street>Anadel Road</Street>
        <HouseNo>46</HouseNo>
        <PostCode>W42 RA</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Lone Castle Road</Street>
        <HouseNo>65</HouseNo>
        <PostCode>W41 BH</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>30</EstimatedTime>
    <Name>Matthew</Name>
    <PhoneNumber>07555451255</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Regular">
        <RegularBooking>
            <ClientID>7</ClientID>
            <RepeatOn>
			    <DriverID>15</DriverID>
                <WeekDay>WEDNESDAY</WeekDay>
                <WeeklyInterval>1</WeeklyInterval>
                <PickUpTime>13:00:00</PickUpTime>
                <PickUpDate>2012-12-26</PickUpDate>
                <RegStatus>ONGOING</RegStatus>
				<TimesComplete>0</TimesComplete>
            </RepeatOn>
        </RegularBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>2</OperatorID>
    <BookingDate>2012-12-10</BookingDate>
    <BookingTime>17:30:00</BookingTime>
    <PickUpAddress>
        <Street>Silver Flower Street</Street>
        <HouseNo>2</HouseNo>
        <PostCode>W12 0TE</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Sleepy Hickory Road</Street>
        <HouseNo>6</HouseNo>
        <PostCode>W1B 1AH</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>120</EstimatedTime>
    <Name>Cane</Name>
    <PhoneNumber>07555412275</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Normal">
       <NormalBooking>
	        <DriverID>2</DriverID>
			<PickUpDate>2012-12-06</PickUpDate>
    		<PickUpTime>19:00:00</PickUpTime>
	  </NormalBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking9.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>4</OperatorID>
    <BookingDate>2012-12-11</BookingDate>
    <BookingTime>19:22:00</BookingTime>
    <PickUpAddress>
        <Street>Roman Street</Street>
        <HouseNo>75</HouseNo>
        <PostCode>W41 LU</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Amber Trace Street</Street>
        <HouseNo>56</HouseNo>
        <PostCode>W13 9RR</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>30</EstimatedTime>
    <Name>Thomas</Name>
    <PhoneNumber>07555451275</PhoneNumber>
    <Status>NOT COMPLETE</Status>
    <BookingInfo Type="Regular">
        <RegularBooking>
            <ClientID>4</ClientID>
            <RepeatOn>
			    <DriverID>13</DriverID>
                <WeekDay>SATURDAY</WeekDay>
                <WeeklyInterval>4</WeeklyInterval>
                <PickUpTime>16:10:00</PickUpTime>
                <PickUpDate>2012-12-15</PickUpDate>
                <RegStatus>ONGOING</RegStatus>
				<TimesComplete>5</TimesComplete>
            </RepeatOn>
        </RegularBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking11.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>5</OperatorID>
    <BookingDate>2012-12-12</BookingDate>
    <BookingTime>09:21:00</BookingTime>
    <PickUpAddress>
        <Street>Little Branch Road</Street>
        <HouseNo>2</HouseNo>
        <PostCode>W12 0QG</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Sunny Bluff Road</Street>
        <HouseNo>51</HouseNo>
        <PostCode>W71 DA</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>50</EstimatedTime>
    <Name>George</Name>
    <PhoneNumber>07555412275</PhoneNumber>
    <Status>CANCELLED</Status>
    <BookingInfo Type="Normal">
      <NormalBooking>
			<DriverID>12</DriverID>
			<ClientID>7</ClientID>
			<PickUpDate>2012-12-08</PickUpDate>
    		<PickUpTime>09:33:00</PickUpTime>
	  </NormalBooking>
    </BookingInfo>
</Booking>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Bookings/booking12.xml
<?xml version="1.0" encoding="UTF-8"?>
<Booking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Booking.xsd">
    <OperatorID>6</OperatorID>
    <BookingDate>2012-12-12</BookingDate>
    <BookingTime>23:22:00</BookingTime>
    <PickUpAddress>
        <Street>Lone Castle Road</Street>
        <HouseNo>65</HouseNo>
        <PostCode>W41 BH</PostCode>
		<City>London</City>
    </PickUpAddress>
    <DestinationAddress>
        <Street>Anadel Road</Street>
        <HouseNo>46</HouseNo>
        <PostCode>W42RA</PostCode>
		<City>London</City>
    </DestinationAddress>
	<EstimatedTime>30</EstimatedTime>
    <Name>Nickolson</Name>
    <PhoneNumber>07553251275</PhoneNumber>
    <Status>COMPLETE</Status>
    <BookingInfo Type="Normal">
        <NormalBooking>
		    <DriverID>12</DriverID>
			<ClientID>7</ClientID>
			<PickUpDate>2012-12-09</PickUpDate>
    		<PickUpTime>08:00:00</PickUpTime>
	  </NormalBooking>
    </BookingInfo>
</Booking>
