=== arturzxc/SQL_XML_DB_TaxiCompany/XSD/Client.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Client">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CompanyName" type="xs:string"/>
                <xs:element name="ClientType">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Private"/>
                            <xs:enumeration value="Corporate"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Discount" type="xs:double"/>
                <xs:group ref="Address"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:group name="Address">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="1" name="Street" type="xs:string"/>
            <xs:element maxOccurs="1" minOccurs="1" name="HouseNo" type="xs:string"/>
            <xs:element maxOccurs="1" minOccurs="0" name="County" type="xs:string"/>
            <xs:element maxOccurs="1" minOccurs="1" name="PostCode" type="xs:string"/>
            <xs:element maxOccurs="1" minOccurs="0" name="City" type="xs:string"/>
        </xs:sequence>
    </xs:group>
</xs:schema>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Clients/client3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Client.xsd">
    <CompanyName>The Peaceful Zebra Devs</CompanyName>
    <ClientType>Private</ClientType>
    <Discount>6.5</Discount>
    <Street>Emerald Lake Orchard Road</Street>
    <HouseNo>14</HouseNo>
    <PostCode>W11 9AQ</PostCode>
	<City>London</City>
</Client>
