=== arturzxc/SQL_XML_DB_TaxiCompany/XSD/Client.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Client">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CompanyName" type="xs:string"/>
                <xs:element name="ClientType">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Private"/>
                            <xs:enumeration value="Corporate"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Discount" type="xs:double"/>
                <xs:group ref="Address"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:group name="Address">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="1" name="Street" type="xs:string"/>
            <xs:element maxOccurs="1" minOccurs="1" name="HouseNo" type="xs:string"/>
            <xs:element maxOccurs="1" minOccurs="0" name="County" type="xs:string"/>
            <xs:element maxOccurs="1" minOccurs="1" name="PostCode" type="xs:string"/>
            <xs:element maxOccurs="1" minOccurs="0" name="City" type="xs:string"/>
        </xs:sequence>
    </xs:group>
</xs:schema>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Clients/client6.xml
<?xml version="1.0" encoding="UTF-8"?>
<Client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Client.xsd">
    <CompanyName>Beta Tomato Marketing</CompanyName>
    <ClientType>Corporate</ClientType>
    <Discount>2.5</Discount>
    <Street>Lone Castle Road</Street>
    <HouseNo>65</HouseNo>
    <PostCode>W41 BH</PostCode>
	<City>London</City>
</Client>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Clients/client4.xml
<?xml version="1.0" encoding="UTF-8"?>
<Client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Client.xsd">
    <CompanyName>Tall Cow Devs</CompanyName>
    <ClientType>Corporate</ClientType>
    <Discount>10</Discount>
    <Street>Orange Snake Road</Street>
    <HouseNo>53</HouseNo>
    <PostCode>W14 0ZN</PostCode>
	<City>London</City>
</Client>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Clients/client1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Client.xsd">
    <CompanyName>Maddison Engineering</CompanyName>
    <ClientType>Private</ClientType>
    <Discount>2.5</Discount>
    <Street>Manchester Street</Street>
    <HouseNo>54</HouseNo>
    <PostCode>W1K 4JU</PostCode>
	<City>London</City>
</Client>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Clients/client2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Client.xsd">
    <CompanyName>Big Baboon Web Design</CompanyName>
    <ClientType>Corporate</ClientType>
    <Discount>1.5</Discount>
    <Street>Sunny Run Street</Street>
    <HouseNo>61</HouseNo>
    <PostCode>W1K 3EP</PostCode>
	<City>London</City>
</Client>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Clients/client8.xml
<?xml version="1.0" encoding="UTF-8"?>
<Client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Client.xsd">
    <CompanyName>White Box Builders</CompanyName>
    <ClientType>Corporate</ClientType>
    <Discount>2</Discount>
    <Street>Rustic Anchor Street</Street>
    <HouseNo>41</HouseNo>
    <PostCode>W1D 2DS</PostCode>
	<City>London</City>
</Client>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Clients/client7.xml
<?xml version="1.0" encoding="UTF-8"?>
<Client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Client.xsd">
    <CompanyName>The Content Panda Company</CompanyName>
    <ClientType>Private</ClientType>
    <Discount>3.3</Discount>
    <Street>Sleepy Point Street</Street>
    <HouseNo>43</HouseNo>
    <PostCode>W36 JH</PostCode>
	<City>London</City>
</Client>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Clients/client5.xml
<?xml version="1.0" encoding="UTF-8"?>
<Client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Client.xsd">
    <CompanyName>The Small Tree Engineers</CompanyName>
    <ClientType>Private</ClientType>
    <Discount>11</Discount>
    <Street>Big Vale Street</Street>
    <HouseNo>12</HouseNo>
    <PostCode>W52 SZ</PostCode>
	<City>London</City>
</Client>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Clients/client9.xml
<?xml version="1.0" encoding="UTF-8"?>
<Client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://group17.99k.org/Client.xsd">
    <CompanyName>Black Builders Co</CompanyName>
    <ClientType>Private</ClientType>
    <Discount>5</Discount>
    <Street>Bishop Street</Street>
    <HouseNo>66</HouseNo>
    <PostCode>W1A 3WZ</PostCode>
	<City>London</City>
</Client>
