=== arturzxc/SQL_XML_DB_TaxiCompany/XSD/Employee.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="employee">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="firstname" type="xs:string"/>
        <xs:element name="lastname" type="xs:string"/>
        <xs:element name="address">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="house" type="xs:string"/>
              <xs:element name="street" type="xs:string"/>
              <xs:element name="postcode" type="xs:string"/>
              <xs:element name="town" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="phone" type="xs:string"/>
        <xs:element name="ratetype" type="xs:string"/>
        <xs:element name="ratevalue" type="xs:string"/>
        <xs:element name="hire" type="xs:date"/>
        <xs:element name="shift" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/7.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Rae</firstname>
	<lastname>Freda</lastname>
	<address>
		<house>44</house>
		<street>Shenley Road</street>
		<postcode>W1H1BX</postcode>
		<town>London</town>
	</address>
	<phone>02089721494</phone>
	<ratetype>S</ratetype>
	<ratevalue>15</ratevalue>
	<hire>2012-12-10</hire>
	<shift>4</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Clinton</firstname>
	<lastname>Beitz</lastname>
	<address>
		<house>23</house>
		<street>Queensbury Street</street>
		<postcode>W139TY</postcode>
		<town>London</town>
	</address>
	<phone>07433127445</phone>
	<ratetype>S</ratetype>
	<ratevalue>30</ratevalue>
	<hire>2012-12-10</hire>
	<shift>20</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/6.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Jonas</firstname>
	<lastname>Brothers</lastname>
	<address>
		<house>66</house>
		<street>Eten Street</street>
		<postcode>W1K1AN</postcode>
		<town>London</town>
	</address>
	<phone>07889121495</phone>
	<ratetype>S</ratetype>
	<ratevalue>20</ratevalue>
	<hire>2012-12-10</hire>
	<shift>3</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Louis</firstname>
	<lastname>Bend</lastname>
	<address>
		<house>44</house>
		<street>Granville Place</street>
		<postcode>W84QX</postcode>
		<town>London</town>
	</address>
	<phone>07539121495</phone>
	<ratetype>F</ratetype>
	<ratevalue>8</ratevalue>
	<hire>2012-12-10</hire>
	<shift>1</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/12.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Odessa</firstname>
	<lastname>Perugini</lastname>
	<address>
		<house>75</house>
		<street>Roman Street</street>
		<postcode>W41LU</postcode>
		<town>London</town>
	</address>
	<phone>07884151895</phone>
	<ratetype>F</ratetype>
	<ratevalue>6</ratevalue>
	<hire>2012-12-10</hire>
	<shift>32</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/19.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Tom</firstname>
	<lastname>Maxez</lastname>
	<address>
		<house>44</house>
		<street>Granville Place</street>
		<postcode>W84QX</postcode>
		<town>London</town>
	</address>
	<phone>07834359895</phone>
	<ratetype>F</ratetype>
	<ratevalue>7.5</ratevalue>
	<hire>2012-12-10</hire>
	<shift>39</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/14.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Marly</firstname>
	<lastname>Hunt</lastname>
	<address>
		<house>66</house>
		<street>Bishop Street</street>
		<postcode>W1A3WZ</postcode>
		<town>London</town>
	</address>
	<phone>07885358895</phone>
	<ratetype>F</ratetype>
	<ratevalue>6</ratevalue>
	<hire>2012-12-10</hire>
	<shift>54</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/23.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Mike</firstname>
	<lastname>Sadur</lastname>
	<address>
		<house>54</house>
		<street>Quinse Road</street>
		<postcode>W1F7PL</postcode>
		<town>London</town>
	</address>
	<phone>07834359895</phone>
	<ratetype>F</ratetype>
	<ratevalue>7.5</ratevalue>
	<hire>2012-12-10</hire>
	<shift>13</shift>
</employee>
