=== arturzxc/SQL_XML_DB_TaxiCompany/XSD/Employee.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="employee">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="firstname" type="xs:string"/>
        <xs:element name="lastname" type="xs:string"/>
        <xs:element name="address">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="house" type="xs:string"/>
              <xs:element name="street" type="xs:string"/>
              <xs:element name="postcode" type="xs:string"/>
              <xs:element name="town" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="phone" type="xs:string"/>
        <xs:element name="ratetype" type="xs:string"/>
        <xs:element name="ratevalue" type="xs:string"/>
        <xs:element name="hire" type="xs:date"/>
        <xs:element name="shift" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/5.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Miro</firstname>
	<lastname>Karakol</lastname>
	<address>
		<house>15</house>
		<street>Turndown Road</street>
		<postcode>W140NL</postcode>
		<town>London</town>
	</address>
	<phone>07519131495</phone>
	<ratetype>F</ratetype>
	<ratevalue>8</ratevalue>
	<hire>2012-12-10</hire>
	<shift>2</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/9.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Neil</firstname>
	<lastname>Havis</lastname>
	<address>
		<house>1</house>
		<street>Olah Street</street>
		<postcode>W1T4JR</postcode>
		<town>London</town>
	</address>
	<phone>07289441295</phone>
	<ratetype>S</ratetype>
	<ratevalue>30</ratevalue>
	<hire>2012-12-10</hire>
	<shift>5</shift>
</employee>
