=== arturzxc/SQL_XML_DB_TaxiCompany/XSD/Employee.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="employee">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="firstname" type="xs:string"/>
        <xs:element name="lastname" type="xs:string"/>
        <xs:element name="address">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="house" type="xs:string"/>
              <xs:element name="street" type="xs:string"/>
              <xs:element name="postcode" type="xs:string"/>
              <xs:element name="town" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="phone" type="xs:string"/>
        <xs:element name="ratetype" type="xs:string"/>
        <xs:element name="ratevalue" type="xs:string"/>
        <xs:element name="hire" type="xs:date"/>
        <xs:element name="shift" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/17.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Ben</firstname>
	<lastname>Hunt</lastname>
	<address>
		<house>17</house>
		<street>River Syf</street>
		<postcode>W130NQ</postcode>
		<town>London</town>
	</address>
	<phone>07834359895</phone>
	<ratetype>F</ratetype>
	<ratevalue>7.5</ratevalue>
	<hire>2012-12-10</hire>
	<shift>17</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/24.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Mindy</firstname>
	<lastname>Buntler</lastname>
	<address>
		<house>1</house>
		<street>Olah Street</street>
		<postcode>W1T4JR</postcode>
		<town>London</town>
	</address>
	<phone>07834359895</phone>
	<ratetype>F</ratetype>
	<ratevalue>8</ratevalue>
	<hire>2012-12-10</hire>
	<shift>24</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/15.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Mayan</firstname>
	<lastname>Dang</lastname>
	<address>
		<house>12</house>
		<street>Canel Woods Road</street>
		<postcode>W1D4HZ</postcode>
		<town>London</town>
	</address>
	<phone>07845455139</phone>
	<ratetype>F</ratetype>
	<ratevalue>7.5</ratevalue>
	<hire>2012-12-10</hire>
	<shift>75</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/13.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Pengwei</firstname>
	<lastname>Yun</lastname>
	<address>
		<house>32</house>
		<street>Omah Street</street>
		<postcode>W1D5PH</postcode>
		<town>London</town>
	</address>
	<phone>0784425189</phone>
	<ratetype>F</ratetype>
	<ratevalue>6</ratevalue>
	<hire>2012-12-10</hire>
	<shift>43</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Pan</firstname>
	<lastname>Swift</lastname>
	<address>
		<house>5</house>
		<street>Mayhem Road</street>
		<postcode>W144DJ</postcode>
		<town>London</town>
	</address>
	<phone>07289141196</phone>
	<ratetype>S</ratetype>
	<ratevalue>15</ratevalue>
	<hire>2012-12-10</hire>
	<shift>3</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/11.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Ted</firstname>
	<lastname>Kinnison</lastname>
	<address>
		<house>46</house>
		<street>Anadel Road</street>
		<postcode>W42RA</postcode>
		<town>London</town>
	</address>
	<phone>07549223495</phone>
	<ratetype>F</ratetype>
	<ratevalue>6</ratevalue>
	<hire>2012-12-10</hire>
	<shift>11</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Jorge</firstname>
	<lastname>Moreno</lastname>
	<address>
		<house>32</house>
		<street>Mount Hill</street>
		<postcode>W3 8BW</postcode>
		<town>London</town>
	</address>
	<phone>02089121495</phone>
	<ratetype>F</ratetype>
	<ratevalue>7</ratevalue>
	<hire>2012-12-10</hire>
	<shift>1</shift>
</employee>

=== arturzxc/SQL_XML_DB_TaxiCompany/XML/Employees/21.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://group17.99k.org/Employee.xsd">
	<firstname>Mark</firstname>
	<lastname>Hunae</lastname>
	<address>
		<house>66</house>
		<street>Eten Street</street>
		<postcode>W1K1AN</postcode>
		<town>London</town>
	</address>
	<phone>07834359895</phone>
	<ratetype>F</ratetype>
	<ratevalue>7.5</ratevalue>
	<hire>2012-12-10</hire>
	<shift>51</shift>
</employee>
